create table stn_sr_583411_base_upd (organization_name          varchar2(240)
                                    , vendor_id                 number
                                    , vendor_site_id            number
                                    , vendor_name               varchar2(240)
                                    , segment1                  varchar2(30)
                                    , hcp_email_address         varchar2(2000) 
                                    , assa_email_address        varchar2(2000)
                                    , iepa_remit_advice_email   varchar2(2000) 
                                    , party_site_id             number
                                    , flag_hcp_email            varchar2(240)
                                    , msg_hcp_email             varchar2(2000) 
                                    , flag_assa_email           varchar2(240)
                                    , msg_assa_email            varchar2(2000) 
                                    , flag_iepa_email           varchar2(240)
                                    , msg_iepa_email            varchar2(2000)                                     
                                    , msg_erro                  varchar2(2000));

