/*
   Tabelas Gestão de Reagentes
   Desenvolvido por MRI Tecnologia Eletrônica
   Versão para Oracle Server
   ATENÇÃO: Antes de executar este script deve ser executado o script CreateTablesMRI.sql
   Alterações:
   Migração: 05/07/2020
   08/09/2020 Junio: Modificou o o campo Name REAGENT_REGISTER_RMGMT
   08/09/2020 Junio: Adicionou campos em REAGENT_REGISTER_RMGMT (DEGREE_HAZARD, LOCATION, CONCENTRATION, FACTOR, GLASS, REAGENT_COMP)
   09/09/2020 Junio: Modificou/adicionou as triplas concentration e factor
   09/09/2020 Junio: Modificou tipo FISPQ para BLOB
   11/09/2020 Junio: Modificou comprimento do GLASS de 64 para 250
*/
CREATE TABLE REAGENT_REGISTER_RMGMT
(
	IDENTIFIER          INTEGER      NOT NULL,
	COMPANY             INTEGER      NOT NULL,
	NAME                VARCHAR(250) NOT NULL,
	TYPE_REAGENT        INTEGER      DEFAULT 0 NOT NULL,
	FISPQ               BLOB,
	VALIDITY_DAYS       INTEGER      NOT NULL,
	
	MIN_STOCK           NUMBER(12,5) NOT NULL,
	MIN_SK_UNIT_INDEX   INTEGER      NOT NULL,  
	MIN_SK_UNIT_TEXT    VARCHAR(8)   NOT NULL,
	
	CURR_QUANTITY       NUMBER(12,5) DEFAULT 0,
	CURR_UNIT_INDEX     INTEGER,  
	CURR_UNIT_TEXT      VARCHAR(8),
	
	DENSITY             NUMBER(12,5) NOT NULL,
	DENSITY_UNIT_INDEX  INTEGER      NOT NULL,  
	DENSITY_UNIT_TEXT   VARCHAR(8)   NOT NULL,
	
	CONCENTRATION       NUMBER(12, 5),
	CONCENT_UNIT_INDEX  INTEGER,
	CONCENT_UNIT_TEXT   VARCHAR(8),
	
	FACTOR              NUMBER(12, 5),
	FACTOR_UNIT_INDEX   INTEGER,
	FACTOR_UNIT_TEXT    VARCHAR(8),
	
	DEGREE_HAZARD       VARCHAR(128),
	LOCATION            VARCHAR(128),
	
	GLASS               VARCHAR(250),
	REAGENT_COMP        CLOB,
	
	DESCRIPTION         CLOB,
	
	CANCELED            CHAR(1) DEFAULT 'N' NOT NULL,   
	CONSTRAINT PK_CADASTRO_REAGENTES
			   PRIMARY KEY (IDENTIFIER, COMPANY)
);

CREATE TABLE REAGENT_BOTTLES_RMGMT
(
	IDENTIFIER         INTEGER      NOT NULL,
	COMPANY            INTEGER      NOT NULL,
	ID_REAGENT         INTEGER      NOT NULL,
	NF                 VARCHAR(64)  NOT NULL,
	RECEIVING_DATE     DATE         NOT NULL,
	ID_SUPPLIER        INTEGER      NOT NULL,
    BRAND              VARCHAR(32)  NOT NULL,
	SUPPLIER_LOT       VARCHAR(32)  NOT NULL,
	MANUFACT_DATE      DATE         NOT NULL,
	EXPIRATION_DATE    DATE         NOT NULL,
	
	INPUT_QUANTITY     NUMBER(12,5) NOT NULL,
	CURR_QUANTITY      NUMBER(12,5) DEFAULT 0,
		
	UNIT_INDEX         INTEGER      NOT NULL,  
	UNIT_TEXT          VARCHAR(8)   NOT NULL,
	
	END_DATE           DATE,
	
	DENSITY            NUMBER(12,5) NOT NULL,
	DENSITY_UNIT_INDEX INTEGER      NOT NULL,  
	DENSITY_UNIT_TEXT  VARCHAR(8)   NOT NULL,
	
	FINISHED           CHAR(1) DEFAULT 'N' NOT NULL,
	CANCELED           CHAR(1) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_FRASCOS_REAGENTES
	           PRIMARY KEY (IDENTIFIER, COMPANY, RECEIVING_DATE),
	CONSTRAINT FK_ID_REAGENTE_EM_FRASCOS
			   FOREIGN KEY (ID_REAGENT, COMPANY)
			   REFERENCES REAGENT_REGISTER_RMGMT(IDENTIFIER, COMPANY)
);

CREATE TABLE REAGENT_CONSUMPTION_RMGMT
(
	ID_BOTTLE          INTEGER       NOT NULL,
	COMPANY            INTEGER       NOT NULL,
	ID_REAGENT         INTEGER       NOT NULL,
	CONSUMER_DATE      DATE          NOT NULL,
	ID_ANALYST         VARCHAR(32)   NOT NULL,
	
	MOVING_QUANTITY    NUMBER(12,5)  NOT NULL,
	MOVING_UNIT_INDEX  INTEGER       NOT NULL,  
	MOVING_UNIT_TEXT   VARCHAR(8)    NOT NULL,
	
	CURR_QT_BOTTLE     NUMBER(12,5)  NOT NULL,
	BOTTLE_UNIT_INDEX  INTEGER       NOT NULL,  
	BOTTLE_UNIT_TEXT   VARCHAR(8)    NOT NULL,
	
	CURR_QT_TOTAL      NUMBER(12,5)  NOT NULL,
	TOTAL_UNIT_INDEX   INTEGER       NOT NULL,  
	TOTAL_UNIT_TEXT    VARCHAR(8)    NOT NULL,
	
	FLAG_MOVEMENT      CHAR(1)       NOT NULL,
	FLAG_READING       CHAR(1)       NOT NULL,
	ALLEGATION         CLOB,
	CONSTRAINT FK_ID_REAGENTE_EM_CONSUMO
			   FOREIGN KEY (ID_REAGENT, COMPANY)
			   REFERENCES REAGENT_REGISTER_RMGMT(IDENTIFIER, COMPANY)
);