/*    VITOPEL DO BRASIL    */
/* Criação dos schemas para nova aplicação de DW */

/*TABLESPACES*/
CREATE TABLESPACE XV_UTIL_DATA DATAFILE '+DATA/prod/datafile/xv_util_data' SIZE 50M AUTOEXTEND ON;
CREATE TABLESPACE XV_UTIL_IDX DATAFILE  '+DATA/prod/datafile/xv_util_idx' SIZE 50M AUTOEXTEND ON;
CREATE TABLESPACE XV_DW40_DATA DATAFILE '+DATA/prod/datafile/xv_dw40_data' SIZE 50M AUTOEXTEND ON;
CREATE TABLESPACE XV_DW40_IDX DATAFILE  '+DATA/prod/datafile/xv_dw40_idx' SIZE 50M AUTOEXTEND ON;
CREATE TABLESPACE XV_DW40_VAR DATAFILE  '+DATA/prod/datafile/xv_dw40_var' SIZE 50M AUTOEXTEND ON;

/*SCHEMAS*/
CREATE USER XV_UTIL IDENTIFIED BY uL4r1mx DEFAULT TABLESPACE XV_UTIL_DATA;
CREATE USER XV_DW40 IDENTIFIED BY p0r6skf DEFAULT TABLESPACE XV_DW40_DATA;

/*GRANTS*/
GRANT CONNECT, RESOURCE TO XV_UTIL, XV_DW40;
GRANT DEBUG CONNECT SESSION TO XV_UTIL, XV_DW40;
GRANT CREATE TABLE TO XV_DW40;
GRANT SELECT ANY TABLE TO XV_DW40;
GRANT SELECT_CATALOG_ROLE TO XV_DW40;

/*ROLES*/
CREATE ROLE XV_UTIL_DIU NOT IDENTIFIED;
    GRANT XV_UTIL_DIU TO SYSTEM WITH ADMIN OPTION;
    GRANT XV_UTIL_DIU TO XV_UTIL WITH ADMIN OPTION;
    GRANT XV_UTIL_DIU TO IMPMPROD,INTEGRACION,APX_IMPM,XV_DW40;
    
CREATE ROLE XV_UTIL_SEL NOT IDENTIFIED;
    GRANT XV_UTIL_SEL TO SYSTEM WITH ADMIN OPTION;
    GRANT XV_UTIL_SEL TO XV_UTIL WITH ADMIN OPTION; 
    GRANT XV_UTIL_SEL TO IMPMPROD,INTEGRACION,APX_IMPM,XV_DW40;   

CREATE ROLE XV_UTIL_EXE NOT IDENTIFIED;
    GRANT XV_UTIL_EXE TO SYSTEM WITH ADMIN OPTION;
    GRANT XV_UTIL_EXE TO XV_UTIL WITH ADMIN OPTION; 
    GRANT XV_UTIL_EXE TO IMPMPROD,INTEGRACION,APX_IMPM,XV_DW40; 
    