

UPDATE APPS.MTL_CROSS_REFERENCES 
SET ATTRIBUTE_CATEGORY = 'GTIN'
WHERE ATTRIBUTE1 IS NOT NULL 
and cross_reference_type = 'GTIN';

-- 7 rows

UPDATE APPS.MTL_CROSS_REFERENCES 
SET ATTRIBUTE_CATEGORY = 'DUN14'
WHERE ATTRIBUTE2 IS NOT NULL AND CROSS_REFERENCE_TYPE = 'DUN14';

-- 30 rows 

