UPDATE APPS.FND_fORM_CUSTOM_RULES SET ENABLED = 'N', LAST_UPDATED_BY = 2070, LAST_UPDATE_DATE = SYSDATE,DESCRIPTION = DESCRIPTION|| 'Desac C#2217' WHERE
 function_name = 'INV_INVTTMTX_SUBINV' AND SEQUENCE IN (10,20);
