DELETE FROM "Z_APARCOTEMPO";

DROP TABLE Z_APARCOTEMPO;

CREATE TABLE 
"Z_APARCOTEMPO" (
    "Id" varchar(36) NOT NULL,
    "DocumentNumber" varchar(50),
    "Number" NUMBER(10) NOT NULL,
    "StartDate" TIMESTAMP(7) NOT NULL,
    "EndDate" TIMESTAMP(7) NOT NULL,
    "DueDate" TIMESTAMP(7) NOT NULL,
    "ContractId" varchar(150) NOT NULL,
    "ExternalKey" varchar(255) NOT NULL,
    "PartyId" varchar(36) NOT NULL,
    "PartyExternalId" varchar(255),
    "PartyRegisteredNumber" varchar(18),
    "PartyName" varchar(255) NOT NULL,
    "CounterPartyId" varchar(36) NOT NULL,
    "CounterPartyExternalId" varchar(255),
    "CounterPartyRegisteredNumber" varchar(18),
    "CounterPartyName" varchar(255) NOT NULL,
    "PortionCounterPartyId" varchar(36),
    "PortionCounterPartyExternalId" varchar(255),
    "PortionCounterPartyRegNumber" varchar(18),
    "PortionCounterPartyName" varchar(255),
    "InstrumentTicker" varchar(100) NOT NULL,
    "ContractCategory" varchar(50) NOT NULL,
    "ContractCurrency" varchar(3) NOT NULL,
    "SettlementCurrency" varchar(3) NOT NULL,
    "VariationValue" DOUBLE PRECISION NOT NULL,
    "LPCP" varchar(11),
    "PaymentMethod" varchar(17),
    "Portfolio" varchar(255) NOT NULL,
    "Index" varchar(80),
    "Principal" DOUBLE PRECISION NOT NULL,
    "Interest" DOUBLE PRECISION NOT NULL,
    "MarkToMarket" DOUBLE PRECISION NOT NULL,
    "MonetaryCorrection" DOUBLE PRECISION NOT NULL,
    "CEXMonetaryCorrection" DOUBLE PRECISION NOT NULL,
    "CEXNotional" DOUBLE PRECISION NOT NULL,
    "CEXInterest" DOUBLE PRECISION NOT NULL,
    "CEXFee" DOUBLE PRECISION NOT NULL,
    "CEXAmortization" DOUBLE PRECISION NOT NULL,
    "FeeUpfront" DOUBLE PRECISION NOT NULL,
    "InterestLate" DOUBLE PRECISION NOT NULL,
    "InterestFine" DOUBLE PRECISION NOT NULL,
    "Adjustment" DOUBLE PRECISION NOT NULL,
    "BrokerageFee" DOUBLE PRECISION NOT NULL,
    "Emolument" DOUBLE PRECISION NOT NULL,
    "Premium" DOUBLE PRECISION NOT NULL,
    "CommissionValue" DOUBLE PRECISION NOT NULL,
    "Bonus" DOUBLE PRECISION NOT NULL,
    "Ir" DOUBLE PRECISION NOT NULL,
    "Iof" DOUBLE PRECISION NOT NULL,
    "RevertedOn" TIMESTAMP(7) NOT NULL,
    "ConditionType" NUMBER(10) NOT NULL,
    "ConditionReg" NUMBER(10) NOT NULL,
    "ConditionFlag" char(1) NOT NULL,
    "ConditionExp" NUMBER(10) NOT NULL,
    "Field_1" varchar(255),
    "Field_2" varchar(255),
    "Field_3" varchar(255),
    "Field_4" varchar(255),
    "Field_5" varchar(255),
    "Field_6" varchar(255),
    "Field_7" varchar(255),
    "Field_8" varchar(255),
    "Field_9" varchar(255),
    "Field_10" varchar(255),
    "Field_11" varchar(255),
    "Field_12" varchar(255),
    "Field_13" varchar(255),
    "Field_14" varchar(255),
    "Field_15" varchar(255),
    "Field_16" varchar(255),
    "Field_17" varchar(255),
    "Field_18" varchar(255),
    "Field_19" varchar(255),
    "Field_20" varchar(255),
    "Field_21" varchar(255),
    "Field_22" varchar(255),
    "Field_23" varchar(255),
    "Field_24" varchar(255),
    "Field_25" varchar(255),
    CONSTRAINT "PK_Z_APARCOTEMPO" PRIMARY KEY ("Id")
);