CREATE TABLESPACE XSTREAM_ADM_TBS DATAFILE  '+DATA' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE USER XSTRMADMIN IDENTIFIED BY "Vik.d7698"  DEFAULT TABLESPACE xstream_adm_tbs  QUOTA UNLIMITED ON xstream_adm_tbs CONTAINER=ALL;
GRANT CREATE SESSION TO xstrmadmin;

ALTER USER "XSTRMADMIN" DEFAULT ROLE "SELECT_CATALOG_ROLE";

GRANT CREATE SESSION, SET CONTAINER TO XSTRMADMIN;

BEGIN
   DBMS_XSTREAM_AUTH.GRANT_ADMIN_PRIVILEGE(
      grantee                 => 'xstrmadmin',
      privilege_type          => 'CAPTURE',
      grant_select_privileges => TRUE,
      container               => 'ALL');
END;
