UPDATE 
APPS.RCV_TRANSACTIONS_interface SET TRANSACTION_DATE = TO_DATE('01/06/2020','DD/MM/YYYY'),EXPECTED_RECEiPT_DATE  = TO_DATE('01/06/2020','DD/MM/YYYY') WHERE 
RECEIPT_SOURCE_CODE = 'CUSTOMER' AND TO_ORGANIZATION_ID = 3115 AND SOURCE_DOCUMENT_CODE = 'RMA' AND document_num = '1148';

