SET DEFINE OFF;
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('59', '8602', 'CABRAL');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('284', '8603', 'LOPEZ MORIENA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('461', '8604', 'RODRIGUEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('514', '8605', 'AGUILAR');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('627', '8606', 'CARAZZO BARTRONS');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('824', '8607', 'SANCHEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1076', '8608', 'MACKINNON');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1217', '8609', 'RUIZ BORY');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1226', '8610', 'SHORTREDE');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1260', '8611', 'DI DOMENICA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1402', '8612', 'REYES');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1407', '8613', 'PASSERIEU');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1408', '8614', 'DELLA SANTA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1434', '8615', 'DE LUCA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1454', '8616', 'MONTOYA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1467', '8617', 'YACOFSKY');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1478', '8618', 'SIXTO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1488', '8619', 'PAATS');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1880', '8620', 'VALARCHE');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('1959', '8621', 'VIDAL IMIZCOZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('2322', '8622', 'MELONI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('2378', '8623', 'VERCELLESI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('2546', '8624', 'MENDEZ HUERGO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('2588', '8625', 'NUÑEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('2690', '8626', 'ROTTA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('2900', '8627', 'GIANNATTASIO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('2932', '8628', 'MONTI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('2979', '8629', 'TORRES');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3078', '8630', 'HAMMAR ALDATZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3271', '8631', 'BARCA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3273', '8632', 'CURTOSI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3322', '8633', 'LODS');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3515', '8634', 'CITRONI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3525', '8635', 'ALCAIN');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3573', '8636', 'DIAZ VEGA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3579', '8637', 'GALLUCCI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3613', '8638', 'DEL CARRIL FORNIELES');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3620', '8639', 'MACHADO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3632', '8640', 'BARACCA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3680', '8641', 'SILVA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3700', '8642', 'JIMENEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3829', '8643', 'BISOLI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3944', '8644', 'RETONDINI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('3996', '8645', 'PANNUNZIO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4026', '8646', 'PALMA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4058', '8647', 'ARAUJO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4081', '8648', 'PITTALUGA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4083', '8649', 'PETROCELLI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4132', '8650', 'DE NEVARES');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4164', '8651', 'MUSCHIETTI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4190', '8652', 'GREGORINI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4489', '8653', 'PIREZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4490', '8654', 'BUTLER LARRAIN');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4592', '8655', 'RAGGI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4593', '8656', 'STEFANINI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4625', '8657', 'CORDOBA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('4667', '8658', 'RUIZ DIAZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5018', '8659', 'LECONTE BENITEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5036', '8660', 'CERDA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5045', '8661', 'GOLDSCHMIDT');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5054', '8662', 'PLANAS');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5099', '8663', 'BATISTA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5163', '8664', 'BRAUNSTEIN BAYER');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5183', '8665', 'GROSSI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5223', '8666', 'CONTRERAS');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5303', '8667', 'BODINI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5578', '8668', 'DIAZ SAUBIDET');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5601', '8669', 'GALLEANO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5660', '8670', 'URANGA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5671', '8671', 'JAZHAL');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5672', '8672', 'CORDONI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5678', '8673', 'FERNANDEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5785', '8674', 'STELLA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5867', '8675', 'MARTINEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5907', '8676', 'GIL');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('5921', '8677', 'DE LA FUENTE');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7106', '8678', 'STELLA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7277', '8679', 'DI FRANCESCO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7285', '8680', 'BARROS');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7297', '8681', 'MUYERUANE');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7299', '8682', 'GODINA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7300', '8683', 'SANTI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7303', '8684', 'LO TARTARO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7317', '8685', 'ORDOÑEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7329', '8686', 'DEL CARRIL');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7350', '8687', 'BERASATEGUI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7454', '8688', 'DIEZ PEÑA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7560', '8689', 'VAZQUEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7563', '8690', 'LIENDO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7651', '8691', 'GORORDO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7702', '8692', 'ESTIVARIZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7723', '8693', 'ROSAS');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7733', '8694', 'KISNER');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7735', '8695', 'PERCIAVALLE');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7773', '8696', 'ROBLEDO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7799', '8697', 'PRIMERO NARVAEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7814', '8698', 'BELLO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7815', '8699', 'TAQUINI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7862', '8700', 'FRIEDERICH');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7875', '8701', 'REMISCHEVSKY');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('7940', '8702', 'BOZZI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8052', '8703', 'GARCIA LLORENTE');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8055', '8704', 'PEDEVILLA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8092', '8706', 'MORRESI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8111', '8707', 'BREIDE OBEID');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8126', '8708', 'LAXAGUE');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8137', '8709', 'ROMERO YAJIMA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8140', '8710', 'LACHE SALAMANCA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8156', '8711', 'PRADO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8157', '8712', 'HUNTER');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8256', '8713', 'D`ADDINO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8268', '8714', 'CUETO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8282', '8715', 'GOLLINO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8300', '8716', 'NOCETI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8338', '8717', 'CASAS');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8339', '8718', 'CABELLO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8357', '8719', 'QUATTORDIO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8381', '8720', 'VALENTI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8394', '8721', 'MONTENEGRO FEDUZKA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8401', '8722', 'PETAZZI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8409', '8723', 'TERZA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8417', '8724', 'RODRIGUEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8428', '8725', 'EUSEVI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8463', '8726', 'APALDETTI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8477', '8727', 'MADEO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('8522', '8728', 'MEDINA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9410', '8729', 'MOBILI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9420', '8730', 'ALLEN');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9474', '8731', 'CASALONE');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9477', '8732', 'FALCONE');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9523', '8733', 'NAVEIRA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9572', '8734', 'ORELLANA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9576', '8735', 'TOMSIN');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9578', '8736', 'CARABIO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9591', '8737', 'ROQUIER');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9605', '8738', 'LOPEZ EIZENBERG');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9621', '8739', 'SCHIAVONE');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9627', '8740', 'SALMEN');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9654', '8741', 'FORCLAZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9657', '8742', 'HEREDIA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9686', '8744', 'RIGOLI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9692', '8745', 'REVELLI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9695', '8746', 'DZEMBROWSKI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9699', '8747', 'PERROTTA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9708', '8748', 'MAZZANTI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9709', '8749', 'GOYECHEA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9710', '8750', 'CENDON');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9717', '8751', 'ZAMORA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9725', '8752', 'LANUSSE');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9726', '8753', 'YACOB');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9737', '8755', 'CARMAN');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9739', '8756', 'OTTA WARTANIAN');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9744', '8757', 'DEL CARRIL');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9768', '8758', 'FLYNN');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9769', '8759', 'SANCHEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9770', '8760', 'SAENZ DE MIERA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9776', '8761', 'TOBAL');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9778', '8762', 'IGLESIAS');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9794', '8763', 'REYES BUITRAGO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9799', '8764', 'SCHWINDT');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9814', '8765', 'SANCHEZ');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9850', '8766', 'LAPHITZONDO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9852', '8767', 'DI SERIO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9855', '8768', 'PEREYRA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9866', '8769', 'CROCCO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9868', '8770', 'ALCORTA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9869', '8771', 'PIAZZA VERNET BASUALDO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9890', '8772', 'HUVIEDO');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9891', '8773', 'QUIROGA VERGARA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9900', '8774', 'SEGOVIA');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9903', '8775', 'FUMASONI');
Insert into XX_NEXUS_LEGAJOS
   (LEGAJO_VIEJO, LEGAJO_NUEVO, APELLIDO)
 Values
   ('9910', '8776', 'MATELICA');
COMMIT;
