CREATE INDEX XXSTN.GL_COMB_LASTUPATE_N1 ON GL.GL_CODE_COMBINATIONS (last_update_date);
CREATE INDEX XXSTN.GL_PER_LASTUPATE_N1 ON GL.GL_PERIOD_STATUSES (last_update_date);
CREATE INDEX XXSTN.GL_BAT_LASTUPATE_N1 ON GL.GL_JE_BATCHES (last_update_date);
CREATE INDEX XXSTN.GL_HEAD_LASTUPATE_N1 ON GL.GL_JE_HEADERS (last_update_date);
CREATE INDEX XXSTN.GL_BAL_LASTUPATE_N1 ON GL.GL_BALANCES (last_update_date);
CREATE INDEX XXSTN.GL_LIN_LASTUPATE_N1 ON GL.GL_JE_LINES (last_update_date);